### ISSUE TITLE
hi, estraverse has support es6

### ISSUE THREAD

**Issue by albin3** [estools/esshorten#10]
I use esmangle to minify my code file. It throws an error when my code has ES6 syntax. The error seems caused by [estraverse@1.5.0](https://github.com/estools/estraverse/tree/1.5.0). [estraverse](https://github.com/estools/estraverse) has released to v4.1.1 and it is support es6 syntax.

I just update estraverse to v4.1.1 and pass test case in your project. Would you update estraverse to v4.1.1?

**Comment by albin3** [comment]
@michaelficarra 😄

**Comment by albin3** [comment]
@Constellation 😄

**Comment by mathiasbynens** [comment]
39ca928d3319eb6f6f45d8e23db90c6ef2d01abc

@albin3 Can you try using the latest version from `master`? https://docs.npmjs.com/files/package.json#git-urls-as-dependencies Let us know if this solves your problem.

**Comment by albin3** [comment]
hi, @mathiasbynens i use esmangle to finish my job, and will issue esmangle with this message.
I don't know if esmangle care for the git urls as dependencies style of writing.
btw, do you know the author of esmangle? I think it will be easier with your help😄. thx.

**Comment by michaelficarra** [comment]
@albin3 The original author of esmangle is @Constellation, but the whole @estools team helps maintain it now.

**Comment by albin3** [comment]
wonderful, thx @michaelficarra

**Comment by mathiasbynens** [comment]
Closing in favor of #113. @michaelficarra or @Constellation, could you publish a new version please?

**Comment by Constellation** [comment]
OK, I'll release it :D

**Comment by albin3** [comment]
@Constellation would you resolve this issue in esmangle too? 😄 https://github.com/estools/esmangle/issues/113
thx very much.
