### ISSUE TITLE
Ignore names list

### ISSUE THREAD

**Issue by magalhas** [estools/esshorten#5]
It would be nice to be possible to ignore some names from being renamed. Is a PR welcome?

**Comment by michaelficarra** [comment]
Yes. Please have the interface accept a predicate instead of a finite list of names.

**Comment by magalhas** [comment]
Do you mean a callback that is executed whenever a name is being targeted?

**Comment by michaelficarra** [comment]
[Yes](https://en.wikipedia.org/wiki/Predicate_(mathematical_logic)).

**Comment by magalhas** [comment]
:+1:

**Comment by magalhas** [comment]
I'll close this since the PR was already accepted.
